{{- range $key, $application := .Values.applications }}
---
# Application: {{ $key }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $application.project | default $.Values.global.destination.project | default "default" }}
  source:
    path: {{ $application.path | default $key }}
    repoURL: {{ $application.repoURL | default $.Values.global.source.repoURL }}
    targetRevision: {{ $application.targetRevision | default $.Values.global.source.targetRevision | default "HEAD"}}
    {{- if $application.application_source_specific_configs }}
{{ toYaml $application.application_source_specific_configs | indent 4 }}
    {{- end }}
  destination:
    namespace: {{ $application.namespace | default $key }}
    server: {{ $application.server | default $.Values.global.destination.server | default "https://kubernetes.default.svc" }}
  syncPolicy:
    automated:
      prune: true
{{- end }}
