kind: Deployment
apiVersion: apps/v1
metadata:
  name: prow-pipeline
  namespace: {{ $.Values.prow_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prow-pipeline
  template:
    metadata:
      labels:
        app: prow-pipeline
    spec:
      serviceAccount: prow-pipeline
      containers:
      - name: pipeline
        #image: gcr.io/k8s-testimages/pipeline:latest  # Note: not gcr.io/k8s-prow for dev
        image: gcr.io/k8s-prow/pipeline:v20200209-98f6243d9
        imagePullPolicy: Always  # Good practice for dev/debugging, bad for prod
---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: prow-pipeline
  namespace: {{ $.Values.prow_namespace }}
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-pipeline
rules:
- apiGroups:
  - pipeline.tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  - prowjobs/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prow-pipeline
subjects:
- kind: ServiceAccount
  name: prow-pipeline
  namespace: {{ $.Values.prowjob_namespace }}
