# Namespace for prow
prow_namespace: prow

# Namespace for prow jobs
prowjob_namespace: prowjob

prow_oauth_token: my_secret_prow_oauth_token

prow_hmac_token: my_secret_prow_hmac_token

prow_host: prow.myexample.com

ingressCertificate: my_certificate_secret

prow_plugins:
  plugins:
    ruzickap:
      - size
      - label
      - hold
      - assign
      - blunderbuss
      - lifecycle
      - verify-owners
      - wip
      - trigger

    ruzickap/magma:
      - approve
      - lgtm

  lgtm:
    - repos:
      - ruzickap/magma
      review_acts_as_lgtm: true

prow_config:
  prowjob_namespace: default
  pod_namespace: test-pods
  log_level: debug

  tide:
    merge_method:
      ruzickap/magma: squash
    queries:
      - repos:
          - ruzickap/magma
        labels:
          - lgtm
          - approved
        missingLabels:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
    target_url: https://prow.magmaci.magma.mirantis.tech/tide
    context_options:
      from-branch-protection: false
      skip-unknown-contexts: true

  sinker:
    resync_period: 1m
    max_prowjob_age: 2h
    max_pod_age: 6h

  plank:
    allow_cancellations: true
    job_url_prefix_config:
      '*': https://prow.magmaci.magma.mirantis.tech/view/gcs
    pod_pending_timeout: 60m
    default_decoration_configs:
      '*':
        timeout: 2h
        grace_period: 15s
        utility_images:
          clonerefs: "gcr.io/k8s-prow/clonerefs:v20200127-357360d05"
          initupload: "gcr.io/k8s-prow/initupload:v20200127-357360d05"
          entrypoint: "gcr.io/k8s-prow/entrypoint:v20200127-357360d05"
          sidecar: "gcr.io/k8s-prow/sidecar:v20200127-357360d05"

  deck:
    spyglass:
      size_limit: 500000000 # 500MB
      viewers:
        "started.json|finished.json": ["metadata-viewer"]
        "build-log.txt": ["build-log-viewer"]

  periodics:
    - interval: 10m
      agent: kubernetes
      name: echo-test
      spec:
        containers:
          - image: alpine
            command: ["/bin/date"]
